services:
    wizbii.demo.mongo:
        class: 'Wizbii\DemoBundle\Mongo\MongoBasicDao'

    wizbii.pipeline.stores.conversation:
        class: 'Wizbii\DemoBundle\Store\ConversationStore'
        properties:
            mongoBasicDao: '@wizbii.demo.mongo'

    wizbii.pipeline.stores.user_messages:
        class: 'Wizbii\DemoBundle\Store\UserMessagesStore'
        properties:
            mongoBasicDao: '@wizbii.demo.mongo'

    wizbii.pipeline.spam.detector:
        class: 'Wizbii\DemoBundle\Spam\SpammerDetector'

    wizbii.pipeline.spam.killer:
        class: 'Wizbii\DemoBundle\Spam\SpammerKiller'