wizbii_pipeline:
    name: "profile_pipeline"

    connection:
        host:     '%wizbii.rabbitmq.domain%'
        port:     %wizbii.rabbitmq.port%
        user:     '%wizbii.rabbitmq.user%'
        password: '%wizbii.rabbitmq.password%'
        vhost:    '/'

    actions:
        message_created: ~
        message_deleted: ~
        spammer_detected: ~

    stores:
        # This store updates the conversation
        conversation_store:
            service: wizbii.pipeline.stores.conversation
            triggered_by_actions:
                - message_created
                - message_deleted

        # This store updates a projection containing all messages sent by one user
        user_store:
            service: wizbii.pipeline.stores.user_messages
            triggered_by_actions:
                - message_created
                - message_deleted

        # This store trigger an event for another system when a user is considered a spammer
        spammer_detector:
            service: wizbii.pipeline.spam.detector
            triggered_by_stores:
                - user_store
            triggered_event: 'spammer_detected'

        # This store manages spammer...
        spammer_killer:
            service: wizbii.pipeline.spam.killer
            triggered_by_actions:
                - spammer_detected